# -*- coding: utf-8 -*-
"""credit_card_codsoft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dPnN6PKXP0sKZng7E7yv2DUNNV-KVyS
"""

import pandas as pd
import numpy as np
import sklearn

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

import kagglehub

# Download latest version
path = kagglehub.dataset_download("kartik2112/fraud-detection")

print("Path to dataset files:", path)

df_train = pd.read_csv("/kaggle/input/fraud-detection/fraudTrain.csv")

df_train.head()

print(df_train.isnull().sum())

df_test = pd.read_csv("/kaggle/input/fraud-detection/fraudTest.csv")
df_test.head()

print(df_test.isnull().sum())

print(df_train.shape)

print(df_train.info)

print(df_test.info)

def clean_data(clean):
     clean.drop(['trans_date_trans_time',"Unnamed: 0",'cc_num','first', 'last', 'street', 'city', 'state', 'zip', 'dob', 'trans_num'],axis=1, inplace=True)
     clean.dropna()
     return clean

clean_data(df_train)

clean_data(df_test)

categorical_cols = df_train.select_dtypes(include="object").columns
le = LabelEncoder()
for col in categorical_cols:
    df_train[col] = le.fit_transform(df_train[col])

categorical_cols = df_test.select_dtypes(include="object").columns
le = LabelEncoder()
for col in categorical_cols:
    df_test[col] = le.fit_transform(df_test[col])

encoder=LabelEncoder()
def encode(data):
    data['merchant']=encoder.fit_transform(data['merchant'])
    data["category"] = encoder.fit_transform(data["category"])
    data["gender"] = encoder.fit_transform(data["gender"])
    data["job"] = encoder.fit_transform(data["job"])
    return data

encode(df_train)

encode(df_test)

x = df_train.drop("is_fraud", axis=1)
y = df_train["is_fraud"]

x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.1, random_state=42)

model1 = LogisticRegression()
model1.fit(x_train,y_train)

from sklearn.metrics import accuracy_score

# a function for each metric
def acc_score(test, pred):
    acc_ = accuracy_score(test, pred)
    return acc_

# Print the scores
def print_score(test, pred, model):

    print(f"Classifier: {model}")
    print(f"ACCURACY: {accuracy_score(test, pred)}")

y_pred = model1.predict(x_test)
print_score(y_test, y_pred, "Logistic Regression")

model2 = DecisionTreeClassifier()

model2.fit(x_train,y_train)

Y_Pred = model2.predict(x_test)
print_score(y_test, Y_Pred, "Decision Tree")