# -*- coding: utf-8 -*-
"""spam_sms_codsoft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FD76B1egHrTd90IR5FGDlYTDk_QQTSUY
"""

import pandas as pd
import numpy as np
import sklearn

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

import kagglehub

path = kagglehub.dataset_download("uciml/sms-spam-collection-dataset")

print("Path to dataset files:", path)

data = pd.read_csv('/kaggle/input/sms-spam-collection-dataset/spam.csv', encoding='latin-1')

from sklearn.feature_extraction.text import TfidfVectorizer

# Drop irrelevant columns
data = data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1)

# Rename columns
data = data.rename(columns={'v1': 'label', 'v2': 'message'})

# Convert label to numerical
data['label'] = data['label'].map({'ham': 0, 'spam': 1})

# Apply TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=5000) # Limit features to 5000
X = tfidf_vectorizer.fit_transform(data['message'])
y = data['label']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

display(data.head())
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB

# Instantiate models
logistic_regression_model = LogisticRegression(random_state=42)
svm_model = SVC(kernel='linear', random_state=42)
naive_bayes_model = MultinomialNB()

print("Logistic Regression model instantiated.")
print("Support Vector Machine model instantiated.")
print("Naive Bayes model instantiated.")

logistic_regression_model.fit(X_train, y_train)
svm_model.fit(X_train, y_train)
naive_bayes_model.fit(X_train, y_train)

print("Logistic Regression model trained.")
print("Support Vector Machine model trained.")
print("Naive Bayes model trained.")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Make predictions on the test set
lr_predictions = logistic_regression_model.predict(X_test)
svm_predictions = svm_model.predict(X_test)
nb_predictions = naive_bayes_model.predict(X_test)

# Evaluate Logistic Regression
lr_accuracy = accuracy_score(y_test, lr_predictions)
lr_precision = precision_score(y_test, lr_predictions)
lr_recall = recall_score(y_test, lr_predictions)
lr_f1 = f1_score(y_test, lr_predictions)

print("--- Logistic Regression Metrics ---")
print(f"Accuracy: {lr_accuracy:.4f}")
print(f"Precision: {lr_precision:.4f}")
print(f"Recall: {lr_recall:.4f}")
print(f"F1-score: {lr_f1:.4f}")
print("-" * 30)

# Evaluate SVM
svm_accuracy = accuracy_score(y_test, svm_predictions)
svm_precision = precision_score(y_test, svm_predictions)
svm_recall = recall_score(y_test, svm_predictions)
svm_f1 = f1_score(y_test, svm_predictions)

print("--- SVM Metrics ---")
print(f"Accuracy: {svm_accuracy:.4f}")
print(f"Precision: {svm_precision:.4f}")
print(f"Recall: {svm_recall:.4f}")
print(f"F1-score: {svm_f1:.4f}")
print("-" * 30)

# Evaluate Naive Bayes
nb_accuracy = accuracy_score(y_test, nb_predictions)
nb_precision = precision_score(y_test, nb_predictions)
nb_recall = recall_score(y_test, nb_predictions)
nb_f1 = f1_score(y_test, nb_predictions)

print("--- Naive Bayes Metrics ---")
print(f"Accuracy: {nb_accuracy:.4f}")
print(f"Precision: {nb_precision:.4f}")
print(f"Recall: {nb_recall:.4f}")
print(f"F1-score: {nb_f1:.4f}")
print("-" * 30)